clear all;
close all;


% FILL IN WEIGHTS HERE
W1 = [-0.5 2 -1;
      4 1 -1] ;
W2 = [1 1 -1.5]; 
% W1 = [0 0 0;
%       0 0 0] ;
% W2 = [0 0 0]; 

numData=3;
xData = [1 1 -1; 1 -2 1];


% compute outputs generated by weights using w6hidden and w6output
meshSize = 50;
x1s = linspace(-2.5,2.5,meshSize);
x2s = linspace(-2.5,2.5,meshSize);
[X1 X2] = meshgrid(x1s,x2s);
H = zeros(meshSize,meshSize,2);
O = zeros(meshSize,meshSize);
for i=1:meshSize
    for j=1:meshSize
        H(i,j,:) =  w6hidden(W1, X1(i,j), X2(i,j));
        O(i,j) =  w6output(W1, W2, X1(i,j), X2(i,j));
    end
end
hData = zeros(numData,2);
oData = zeros(numData,1);
for i=1:numData
    hData(i,:) = w6hidden(W1, xData(1,i), xData(2,i))
    oData(i) =  w6output(W1, W2, xData(1,i), xData(2,i))
end
% Plot
gridData = containers.Map({'Hidden 1', 'Hidden 2', 'Output'}, {H(:,:,1), H(:,:,2), O});
pointData = containers.Map({'Hidden 1', 'Hidden 2', 'Output'}, {hData(:,1),hData(:,2),oData});
k = keys(gridData);
gridVal = values(gridData);
pointVal = values(pointData);
for i=1:length(k)
    subplot(1,length(k),i);
    colormap('jet');
    colorbar();
    surf(X1,X2,gridVal{i},'FaceColor', 'none', 'EdgeColor', 'interp');
    hold on;
    scatter3(xData(1,:),xData(2,:),pointVal{i},'filled');
    pbaspect([1 1 1]); 
    caxis([-0.1 1.1]);
    xlim([-2.5 2.5]);
    ylim([-2.5 2.5]);
    xlabel(['x' hex2dec('2081') ' ']);
    ylabel(['x' hex2dec('2082') ' ']);
    zlabel(k{i});
end
set(gcf,'Position',[200,200,1000,400])

function h = w6hidden(W1, x1, x2)
    a = W1 * [x1;x2;1];
    h = [ 1/(1+exp(-a(1))) ; 1/(1+exp(-a(2))) ];
end
function o = w6output(W1, W2, x1, x2)
    h = w6hidden(W1,x1,x2);
    a = W2 * [h;1];
    o = 1/(1+exp(-a));
end

